### ISSUE TITLE
A card with long title has text below action icons

### ISSUE THREAD

**Issue by eduardpeters** [DanNisenson/trello-client#11]
Refer to title. 
<img width="287" alt="image" src="https://user-images.githubusercontent.com/76105887/205717242-595c8c14-31a1-459b-898f-2d209983db2b.png">

**Comment by DanNisenson** [comment]
Now they're hiding but not wrapping.
It was working at some point but broke 😅
gonna fix now

**Comment by DanNisenson** [comment]
Fixed in my last pull req
